### ISSUE TITLE
Make Error use pointer receivers?

### ISSUE THREAD

**Issue by keks** [ipfs/go-ipfs-cmdkit#19]
The type simply represents some data and has only public fields, so it doesn't really make sense to make it a pointer. However, it has an `UnmarshalJSON` method, where we need it to be a pointer.

https://golang.org/doc/faq#methods_on_values_or_pointers suggests that we should be consistent, which would mean that we need to change it to be a pointer type - which goes against it being a "dumb type".

Note that this inconsistency currently is not limited to the receiver type of the methods - go-ipfs-cmds and go-ipfs themselves are pretty inconsistent in their pointer usage with this type.

@Stebalien Do you have opinions on this? Currently I'm leaning towards making it a pointer everywhere.

**Comment by keks** [comment]
Using pointers has the additional benefit that it can be `nil`.

**Comment by keks** [comment]
Actually, how about we make Error an interface with methods `Error() string` and `ErrorCode() ErrorCode`?

**Comment by keks** [comment]
Thinking about this more, I'm confident we should only go for pointers for now.

cc @Stebalien opinions?

**Comment by Stebalien** [comment]
@keks not really.

**Comment by Kubuxu** [comment]
This would require us to provide a method for creating this custom Error type which isn't much better than using `SetError`.

We could be very explicit about it and have multiple return values.

**Comment by keks** [comment]
@Kubuxu 
>This would require us to provide a method for creating this custom Error type 

why would it?
```go
err := &cmdkit.Error{ Message: "an error occurred" }
```

I just want to get some consistency and not always type assert error for both both `cmdkit.Error` and `*cmdkit.Error`.
