### ISSUE TITLE
Should add Int64Option/Uint64Option?

### ISSUE THREAD

**Issue by overbool** [ipfs/go-ipfs-cmdkit#28]
@lgierth should add Int64Option/Uint64Option?
see ipfs/go-ipfs#5380

**Comment by overbool** [comment]
@lgierth  Or should modify IntOption/UintOption to  Int64Option/Uint64Option?

**Comment by Stebalien** [comment]
Let's *add* a new type. However, let's also wait for https://github.com/ipfs/go-ipfs-cmds/pull/112.
