### ISSUE TITLE
Add strings option

### ISSUE THREAD

**Issue by keks** [ipfs/go-ipfs-cmdkit#5]
See https://github.com/ipfs/go-ipfs/pull/4012.

**Comment by overbool** [comment]
@keks If you don't mind, can i try to fix it?

**Comment by keks** [comment]
@overbool O dear, I totally forgot about this one. Reviewing this, I'm not sure whether it's a good idea to have string arrays but not e.g. int arrays. On the other hand I don't want perfect be the enemy of good.

@Stebalien Do you think we should go for strings only or generic array arguments?

**Comment by Stebalien** [comment]
I'd do one per type and we can always just start with strings. However, I'd like to have a *use* for this before we implement it.

**Comment by keks** [comment]
@Stebalien the reason we considered this in the first place was https://github.com/ipfs/go-ipfs/issues/3643.

@overbool looks like you can go ahead on this one

**Comment by Stebalien** [comment]
Got it. Yeah, sounds useful.

**Comment by magik6k** [comment]
It would be useful for the --profile flag as it currently uses a '[hack](https://github.com/ipfs/go-ipfs/blob/master/cmd/ipfs/init.go#L103)' to support multiple profiles
